[tool.pdm]

[project]
name = "Cat-Password"
version = "0.0.1"
description = "Small Password Generator"
authors = [
    {name = "Taras Nytiaha", email = "taras.nytiaha@gmail.com"},
]
dependencies = [
    "pyperclip>=1.8.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
