from typing import Optional

import pyperclip

class GenPassword:
    LENGTH: int = ...
    _SYMBOLS: str = ...
    _SPECIAL_SYMBOLS: str = ...

def __init__(
    self,
    clipboard: pyperclip,
    length: Optional[int] = None,
    seed: Optional[str] = None,
    symbols: Optional[str] = None,
    special_symbols: Optional[str] = None,
) -> None:
    self.clipboard: pyperclip = ...
    if length:
        self.LENGTH: int = ...
    if seed:
        self.sesd: int = ...
    if symbols:
        self._SYMBOLS: int = ...
    if special_symbols:
        self._SPECIAL_SYMBOLS: int = ...

def setup(self) -> None: ...
@property
def _all_symbols(self) -> str: ...
@property
def seed_generator(self) -> str: ...
@property
def _gen_password(self) -> str: ...
@property
def password(self) -> str: ...
